---
title: "icvs_100_ord_results"
author: "Dallas Novakowski"
date: "20/12/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(ordinal)

library(stevemisc) # my toy R package with various helper functions
library(modelr) # for data_grid
library(kableExtra) # for pretty tables
library(dotwhisker)

load(file = "C:/Users/dalla/Google Drive/offline_data_files/icvs_pwt_swiid/data/m100_sims.RData")

load("C:/Users/dalla/Google Drive/offline_data_files/icvs_pwt_swiid/data/mod_joined1.RData")
```

```{r fun}
    # round all numeric variables
round_df <- function(x, digits) {
    numeric_columns <- sapply(x, mode) == 'numeric'
    x[numeric_columns] <-  round(x[numeric_columns], digits)
    x
}
```



```{r store sims}
m100_sims <- m100_sims %>%
  map_df(. %>% as_tibble())

m100_tidy <- tibble(
  term = names(m100_sims),
  estimate = summarise_all(m100_sims, list(mean)) %>%
    t() %>%
    as.vector(),
  std.error = m100_sims %>%
    summarise_all(list(sd)) %>%
    t() %>%
    as.vector()
)

# margin <- qt(0.975,df=n-1)*s/sqrt(n)


# Plot the results
m100_tidy %>%
  by_2sd(mod_joined1) %>%
  relabel_predictors(
    c(
      gini_2004_6_cent = "Income Inequality",
      gdppc_2004_6_scale = "GDP/capita",
      age_cent = "Age",
      employed1 = "Employed",
      male1 = "Male",
      police_effective = "Perceived police effectiveness",
      income_quartile = "Income quartile"
    )
  ) %>%
  dwplot() +
  theme_bw() +
  geom_vline(xintercept = 0,
             colour = "grey60",
             linetype = "dashed") +
  theme(legend.position = "none") +
  labs(title = "Predicting crime victimization",
       x = "Coefficient Estimate")

ggsave(here::here("figures", "ordinal_dotwhisker.png"),
       height = 3)
```


```{r tidykable}
tidy_ci <- m100_tidy %>%
  by_2sd(mod_joined1) %>%
  select(-by_2sd)

tidy_ci$ci95_lo <- tidy_ci$estimate - 1.96*tidy_ci$std.error # = 0.4539815 
tidy_ci$ci95_hi <- tidy_ci$estimate + 1.96*tidy_ci$std.error # = 0.4539815 

tidy_ci$z_score <- tidy_ci$estimate/tidy_ci$std.error #Wald tests
tidy_ci$p_value <-  as.numeric(format(2*pnorm(abs(tidy_ci$z_score), lower.tail=FALSE), scientific = FALSE))

tidy_ci$p_value <-  ifelse(tidy_ci$p_value < .001,
                 "< .001",
                 paste(tidy_ci$p_value %>% round(3)))

tidy_ci <- round_df(tidy_ci, 3)


tidy_ci %>%
  kbl(booktabs = T) %>%
  kable_styling(latex_options = c("striped"))


cgwtools::resave(tidy_ci, file = here::here("output","icvs_output.RData"))

```

